# This is the minimal config file for an NNI experiment.
# Use "nnictl create --config config.yml" to launch this experiment.
# Afterwards, you can check "config_detailed.yml" for more explanation.



authorName: default
experimentName: chao_trial2
trialConcurrency: 1
maxExecDuration: 2h
maxTrialNum: 200
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python SK_Manual1.py
  # command: python3 main1.py
  # command: python3 main1.py
  codeDir: .
  gpuNum: 0